server {
    listen 8080;
    server_name _;

    location /api/catalogue {
        proxy_pass http://catalogue:4001;
        proxy_set_header Host $host;
        proxy_read_timeout 10s;
    }

    location /api/orders {
        proxy_pass http://orders:4002;
        proxy_set_header Host $host;
        proxy_read_timeout 10s;
    }

    location / {
        proxy_pass http://frontend:8080;
        proxy_set_header Host $host;
    }
}
