apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: microservice-app-db
    namespace: microservice-app
    envs:
      - secret.env

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: microservice-app
      namespace: microservice-app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: microservice-app.example.com
