apiVersion: v1
kind: Namespace
metadata:
  name: microshop
  labels:
    app.kubernetes.io/part-of: microshop
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
