apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: catalogue
  namespace: microshop
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalogue
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: orders
  namespace: microshop
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orders
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: microshop
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
