apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: microservice-app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalogue
  namespace: microservice-app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders
  namespace: microservice-app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: microservice-app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-jobs
  namespace: microservice-app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-backup
  namespace: microservice-app
automountServiceAccountToken: false
