apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-monitors.yaml
  - alerts.yaml

configMapGenerator:
  - name: microservice-app-overview-dashboard
    namespace: microservice-app
    files:
      - dashboards/microservice-app-overview.json
    options:
      labels:
        grafana_dashboard: "1"
      disableNameSuffixHash: true
