apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalogue
  namespace: microservice-app
  labels:
    app.kubernetes.io/name: catalogue
    app.kubernetes.io/part-of: microservice-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: catalogue
  namespaceSelector:
    matchNames:
      - microservice-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orders
  namespace: microservice-app
  labels:
    app.kubernetes.io/name: orders
    app.kubernetes.io/part-of: microservice-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: orders
  namespaceSelector:
    matchNames:
      - microservice-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
