apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: microservice-app-db
    namespace: microservice-app
    envs:
      - secret.env

images:
  - name: ghcr.io/lahgolz/microservice-app-catalogue
    newName: microservice-app/catalogue
    newTag: dev
  - name: ghcr.io/lahgolz/microservice-app-orders
    newName: microservice-app/orders
    newTag: dev
  - name: ghcr.io/lahgolz/microservice-app-frontend
    newName: microservice-app/frontend
    newTag: dev
  - name: ghcr.io/lahgolz/microservice-app-db-tools
    newName: microservice-app/db-tools
    newTag: dev

patches:
  - path: replicas.yaml
  - path: hpa.yaml
