apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microshop
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: microshop
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: microshop
spec:
  replicas: 1
