apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microservice-app
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: microservice-app
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: microservice-app
spec:
  replicas: 1
